### ISSUE TITLE
search-api container doesn't respond

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cyber-search#31]
I don't see that search API is responding and there is an exception in stdout:
```
$ docker logs search-api 
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
16:52:21.154 [main] INFO f.cyber.cassandra.CassandraService - Initializing cassandra service
16:52:21.740 [main] INFO f.cyber.cassandra.CassandraService - Initializing cassandra service finished
Exception in thread "main" java.lang.IllegalArgumentException: Table or materialized view address does not exist in keyspace "ethereum_classic"
	at com.datastax.driver.mapping.AnnotationParser.parseEntity(AnnotationParser.java:76)
	at com.datastax.driver.mapping.MappingManager.getMapper(MappingManager.java:273)
	at com.datastax.driver.mapping.MappingManager.mapper(MappingManager.java:232)
	at fund.cyber.cassandra.repository.EthereumKeyspaceRepository.<init>(EthereumKeyspaceRepository.kt:30)
	at fund.cyber.cassandra.CassandraService$ethereumClassicRepository$2.invoke(CassandraService.kt:49)
	at fund.cyber.cassandra.CassandraService$ethereumClassicRepository$2.invoke(CassandraService.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:130)
	at fund.cyber.cassandra.CassandraService.getEthereumClassicRepository(CassandraService.kt)
	at fund.cyber.search.SearchApiApplication.main(SearchApiApplication.kt:19)
```

Port is open, but no response is back:
```
$ curl http://127.0.0.1:32700/ping
curl: (56) Recv failure: Connection reset by peer
```

@hleb-albau, maybe I am using anything wrong?

**Comment by hleb-albau** [comment]
Yeah, right now api requires 4 keyspaces to be initialized in Cassandra. We should refactor api to use initialize keyspace session on demand(lazy).

**Comment by litvintech** [comment]
@YodaMike Please provide description about dependencies with other tasks and flow of this exception

**Comment by YodaMike** [comment]
Code for search api needs to be refactored, there are many places without errors handling. Most part of the code will be modified in tasks #41 and #30, so this issue can be solved indirectly. Anyway we must back to the issue after #41 and #30

**Comment by abitrolly** [comment]
**Acceptance criteria**: we've don't get down in 10 requests per second in week.
