### ISSUE TITLE
Address-service stucks error

### ISSUE THREAD

**Issue by hleb-albau** [cyberFund/cyber-search#36]
```
 11:59:10.329 [pool-1-thread-2] ERROR f.c.a.c.ConvertEntityToAddressDeltaProcess - Calculating ETHEREUM addresses deltas for block 2431515 finished with error
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for ETHEREUM_ADDRESS_DELTA-0: 30002 ms has passed since last attempt plus backoff time
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79) ~[guava-19.0.jar:na]
	at fund.cyber.node.common.ConcurrencyKt.awaitAll(Concurrency.kt:17) ~[common.jar:na]
	at fund.cyber.address.common.ConvertEntityToAddressDeltaProcess.processRecord(ConvertEntityToAddressDeltaProcess.kt:86) ~[address-service.jar:na]
	at fund.cyber.node.kafka.KafkaConsumerRunner.readAndProcessRecords(KafkaConsumerRunner.kt:43) [common.jar:na]
	at fund.cyber.node.kafka.KafkaConsumerRunner.run(KafkaConsumerRunner.kt:24) [common.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for ETHEREUM_ADDRESS_DELTA-0: 30002 ms has passed since last attempt plus backoff time
11:59:10.373 [pool-1-thread-3] ERROR f.c.a.c.ConvertEntityToAddressDeltaProcess - Calculating ETHEREUM addresses deltas for block 2431515 finished with error
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for ETHEREUM_ADDRESS_DELTA-0: 30045 ms has passed since last attempt plus backoff time
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455) ~[guava-19.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79) ~[guava-19.0.jar:na]
	at fund.cyber.node.common.ConcurrencyKt.awaitAll(Concurrency.kt:17) ~[common.jar:na]
	at fund.cyber.address.common.ConvertEntityToAddressDeltaProcess.processRecord(ConvertEntityToAddressDeltaProcess.kt:86) ~[address-service.jar:na]
	at fund.cyber.node.kafka.KafkaConsumerRunner.readAndProcessRecords(KafkaConsumerRunner.kt:43) [common.jar:na]
	at fund.cyber.node.kafka.KafkaConsumerRunner.run(KafkaConsumerRunner.kt:24) [common.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for ETHEREUM_ADDRESS_DELTA-0: 30045 ms has passed since last attempt plus backoff time
11:59:10.381 [pool-1-thread-2] ERROR f.c.node.kafka.KafkaConsumerRunner - consumer record processing error
org.apache.kafka.common.KafkaException: The client hasn't received acknowledgment for some previously sent messages and can no longer retry them. It isn't safe to continue.
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:212) ~[kafka-clients-1.0.0.jar:na]
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:163) ~[kafka-clients-1.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
11:59:10.425 [pool-1-thread-3] ERROR f.c.node.kafka.KafkaConsumerRunner - consumer record processing error
org.apache.kafka.common.KafkaException: The client hasn't received acknowledgment for some previously sent messages and can no longer retry them. It isn't safe to continue. 
```

address service should not stuck, but ether fail or retry.
also, why does this error  occur?

**Comment by abitrolly** [comment]
Is there a description of this address service anywhere?

**Comment by hleb-albau** [comment]
No, i can describe:
Main concept is to calculate address balances, tx count and etc in transaction way. So we have next requirements:
-atomic address updates
-support chain reorganization
-possibility of horizontal scaling

Current implementation uses kafka, to obtains entities provided by pump (tx for bitcoin; tx, block, uncle for ethereum), process then one-be-one. For each item first of all we calculate address fields deltas, and write them back to kafka. For example, for single bitcoin transaction we can write 100 address deltas. Than we apply each delta  on addresses using read before write pattern. 

Also, implementation is not final, see next issue #37

**Comment by hleb-albau** [comment]
Not more actual.
